//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirtySixQuestions.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThirtySixQuestions.Resx.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CongratulationsText {
            get {
                return ResourceManager.GetString("CongratulationsText", resourceCulture);
            }
        }
        
        internal static string CallToActionText {
            get {
                return ResourceManager.GetString("CallToActionText", resourceCulture);
            }
        }
        
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        internal static string ExplanationParagraph1Text {
            get {
                return ResourceManager.GetString("ExplanationParagraph1Text", resourceCulture);
            }
        }
        
        internal static string ExplanationParagraph2Text {
            get {
                return ResourceManager.GetString("ExplanationParagraph2Text", resourceCulture);
            }
        }
        
        internal static string ExplanationParagraph3Text {
            get {
                return ResourceManager.GetString("ExplanationParagraph3Text", resourceCulture);
            }
        }
        
        internal static string MinutesText {
            get {
                return ResourceManager.GetString("MinutesText", resourceCulture);
            }
        }
        
        internal static string SecondsText {
            get {
                return ResourceManager.GetString("SecondsText", resourceCulture);
            }
        }
        
        internal static string ThankYouText {
            get {
                return ResourceManager.GetString("ThankYouText", resourceCulture);
            }
        }
    }
}
