//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirtySixQuestions.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Questions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThirtySixQuestions.Resx.Questions", typeof(Questions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Set1Text {
            get {
                return ResourceManager.GetString("Set1Text", resourceCulture);
            }
        }
        
        internal static string Set2Text {
            get {
                return ResourceManager.GetString("Set2Text", resourceCulture);
            }
        }
        
        internal static string Set3Text {
            get {
                return ResourceManager.GetString("Set3Text", resourceCulture);
            }
        }
        
        internal static string Question01Text {
            get {
                return ResourceManager.GetString("Question01Text", resourceCulture);
            }
        }
        
        internal static string Question02Text {
            get {
                return ResourceManager.GetString("Question02Text", resourceCulture);
            }
        }
        
        internal static string Question03Text {
            get {
                return ResourceManager.GetString("Question03Text", resourceCulture);
            }
        }
        
        internal static string Question04Text {
            get {
                return ResourceManager.GetString("Question04Text", resourceCulture);
            }
        }
        
        internal static string Question05Text {
            get {
                return ResourceManager.GetString("Question05Text", resourceCulture);
            }
        }
        
        internal static string Question06Text {
            get {
                return ResourceManager.GetString("Question06Text", resourceCulture);
            }
        }
        
        internal static string Question07Text {
            get {
                return ResourceManager.GetString("Question07Text", resourceCulture);
            }
        }
        
        internal static string Question08Text {
            get {
                return ResourceManager.GetString("Question08Text", resourceCulture);
            }
        }
        
        internal static string Question09Text {
            get {
                return ResourceManager.GetString("Question09Text", resourceCulture);
            }
        }
        
        internal static string Question10Text {
            get {
                return ResourceManager.GetString("Question10Text", resourceCulture);
            }
        }
        
        internal static string Question11Text {
            get {
                return ResourceManager.GetString("Question11Text", resourceCulture);
            }
        }
        
        internal static string Question12Text {
            get {
                return ResourceManager.GetString("Question12Text", resourceCulture);
            }
        }
        
        internal static string Question13Text {
            get {
                return ResourceManager.GetString("Question13Text", resourceCulture);
            }
        }
        
        internal static string Question14Text {
            get {
                return ResourceManager.GetString("Question14Text", resourceCulture);
            }
        }
        
        internal static string Question15Text {
            get {
                return ResourceManager.GetString("Question15Text", resourceCulture);
            }
        }
        
        internal static string Question16Text {
            get {
                return ResourceManager.GetString("Question16Text", resourceCulture);
            }
        }
        
        internal static string Question17Text {
            get {
                return ResourceManager.GetString("Question17Text", resourceCulture);
            }
        }
        
        internal static string Question18Text {
            get {
                return ResourceManager.GetString("Question18Text", resourceCulture);
            }
        }
        
        internal static string Question19Text {
            get {
                return ResourceManager.GetString("Question19Text", resourceCulture);
            }
        }
        
        internal static string Question20Text {
            get {
                return ResourceManager.GetString("Question20Text", resourceCulture);
            }
        }
        
        internal static string Question21Text {
            get {
                return ResourceManager.GetString("Question21Text", resourceCulture);
            }
        }
        
        internal static string Question22Text {
            get {
                return ResourceManager.GetString("Question22Text", resourceCulture);
            }
        }
        
        internal static string Question23Text {
            get {
                return ResourceManager.GetString("Question23Text", resourceCulture);
            }
        }
        
        internal static string Question24Text {
            get {
                return ResourceManager.GetString("Question24Text", resourceCulture);
            }
        }
        
        internal static string Question25Text {
            get {
                return ResourceManager.GetString("Question25Text", resourceCulture);
            }
        }
        
        internal static string Question26Text {
            get {
                return ResourceManager.GetString("Question26Text", resourceCulture);
            }
        }
        
        internal static string Question27Text {
            get {
                return ResourceManager.GetString("Question27Text", resourceCulture);
            }
        }
        
        internal static string Question28Text {
            get {
                return ResourceManager.GetString("Question28Text", resourceCulture);
            }
        }
        
        internal static string Question29Text {
            get {
                return ResourceManager.GetString("Question29Text", resourceCulture);
            }
        }
        
        internal static string Question30Text {
            get {
                return ResourceManager.GetString("Question30Text", resourceCulture);
            }
        }
        
        internal static string Question31Text {
            get {
                return ResourceManager.GetString("Question31Text", resourceCulture);
            }
        }
        
        internal static string Question32Text {
            get {
                return ResourceManager.GetString("Question32Text", resourceCulture);
            }
        }
        
        internal static string Question33Text {
            get {
                return ResourceManager.GetString("Question33Text", resourceCulture);
            }
        }
        
        internal static string Question34Text {
            get {
                return ResourceManager.GetString("Question34Text", resourceCulture);
            }
        }
        
        internal static string Question35Text {
            get {
                return ResourceManager.GetString("Question35Text", resourceCulture);
            }
        }
        
        internal static string Question36Text {
            get {
                return ResourceManager.GetString("Question36Text", resourceCulture);
            }
        }
    }
}
